### ISSUE TITLE
google-protobuf 4.x doesn't support this gem

### ISSUE THREAD

**Issue by xiaohui-zhangxh** [davissp14/etcdv3-ruby#143]
```ruby
irb(main):003:0> require 'etcdv3'
/usr/local/bundle/gems/etcdv3-0.11.6/lib/etcdv3/etcdrpc/kv_pb.rb:6:in `<top (required)>': undefined method `build' for #<Google::Protobuf::DescriptorPool:0x000072ef554d2f58> (NoMethodError)

Google::Protobuf::DescriptorPool.generated_pool.build do
                                               ^^^^^^
	from /usr/local/bundle/gems/etcdv3-0.11.6/lib/etcdv3/etcdrpc/rpc_pb.rb:6:in `require_relative'
	from /usr/local/bundle/gems/etcdv3-0.11.6/lib/etcdv3/etcdrpc/rpc_pb.rb:6:in `<top (required)>'
	from /usr/local/bundle/gems/etcdv3-0.11.6/lib/etcdv3/etcdrpc/rpc_services_pb.rb:5:in `require_relative'
	from /usr/local/bundle/gems/etcdv3-0.11.6/lib/etcdv3/etcdrpc/rpc_services_pb.rb:5:in `<top (required)>'
	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /usr/local/bundle/gems/etcdv3-0.11.6/lib/etcdv3.rb:4:in `<top (required)>'
	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from (irb):3:in `<main>'
	from /usr/local/lib/ruby/gems/3.2.0/gems/irb-1.6.2/exe/irb:11:in `<top (required)>'
	from /usr/local/bin/irb:25:in `load'
	from /usr/local/bin/irb:25:in `<main>'
```

to fix this, has to uninstall grpc and google-protobuf , reinstall grpc -v 1.64.0

```shell
gem uninstall grpc
gem uninstall google-protobuf
gem install grpc -v 1.64.0
```

**Comment by yungtrizzle** [comment]
according to stackoverflow, it's not even 4.x, it breaks at anything > 3.25.4
https://stackoverflow.com/a/78970516/1254680

**Comment by yungtrizzle** [comment]
looks like we just need to regenerate from the protos: `grpc_tools_ruby_protoc --ruby_out=./etcdrpc --grpc_out=./etcdrpc --proto_path=./protos` run in `lib/etcdv3`

**Comment by yungtrizzle** [comment]
[gogoproto](https://github.com/gogo/protobuf) that is used here is deprecated. that makes regeneration difficult
